// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC54W5E3JcejPIaBeY5g_KsCfSMm8S8KC8',
    appId: '1:882744713161:web:8494666140f6c33b5a9218',
    messagingSenderId: '882744713161',
    projectId: 'eventsapp-flutter',
    authDomain: 'eventsapp-flutter.firebaseapp.com',
    storageBucket: 'eventsapp-flutter.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAGYRTZx6njnk89zdLQN3R1X4Uijbpklt8',
    appId: '1:882744713161:android:044bc0312678e6225a9218',
    messagingSenderId: '882744713161',
    projectId: 'eventsapp-flutter',
    storageBucket: 'eventsapp-flutter.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBMOg4eO2QNsMW8Xf_C63FO8w-X9ZPRfG8',
    appId: '1:882744713161:ios:12674b31b238bc895a9218',
    messagingSenderId: '882744713161',
    projectId: 'eventsapp-flutter',
    storageBucket: 'eventsapp-flutter.appspot.com',
    iosBundleId: 'com.example.eventsAppFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBMOg4eO2QNsMW8Xf_C63FO8w-X9ZPRfG8',
    appId: '1:882744713161:ios:12674b31b238bc895a9218',
    messagingSenderId: '882744713161',
    projectId: 'eventsapp-flutter',
    storageBucket: 'eventsapp-flutter.appspot.com',
    iosBundleId: 'com.example.eventsAppFlutter',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC54W5E3JcejPIaBeY5g_KsCfSMm8S8KC8',
    appId: '1:882744713161:web:b54c916bce664b925a9218',
    messagingSenderId: '882744713161',
    projectId: 'eventsapp-flutter',
    authDomain: 'eventsapp-flutter.firebaseapp.com',
    storageBucket: 'eventsapp-flutter.appspot.com',
  );
}
